/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardWorkerRouteImport } from './routes/dashboard/worker'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DashboardBuyerRouteRouteImport } from './routes/dashboard/buyer/route'
import { Route as DashboardAdminRouteRouteImport } from './routes/dashboard/admin/route'
import { Route as DashboardBuyerIndexRouteImport } from './routes/dashboard/buyer/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardBuyerPurchaseCoinsRouteImport } from './routes/dashboard/buyer/purchase-coins'
import { Route as DashboardBuyerPaymentHistoryRouteImport } from './routes/dashboard/buyer/payment-history'
import { Route as DashboardBuyerMyTaskRouteImport } from './routes/dashboard/buyer/my-task'
import { Route as DashboardBuyerHomeRouteImport } from './routes/dashboard/buyer/home'
import { Route as DashboardBuyerAddTaskRouteImport } from './routes/dashboard/buyer/add-task'
import { Route as DashboardAdminHomeRouteImport } from './routes/dashboard/admin/home'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWorkerRoute = DashboardWorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardBuyerRouteRoute = DashboardBuyerRouteRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminRouteRoute = DashboardAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBuyerIndexRoute = DashboardBuyerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardBuyerRouteRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const DashboardBuyerPurchaseCoinsRoute =
  DashboardBuyerPurchaseCoinsRouteImport.update({
    id: '/purchase-coins',
    path: '/purchase-coins',
    getParentRoute: () => DashboardBuyerRouteRoute,
  } as any)
const DashboardBuyerPaymentHistoryRoute =
  DashboardBuyerPaymentHistoryRouteImport.update({
    id: '/payment-history',
    path: '/payment-history',
    getParentRoute: () => DashboardBuyerRouteRoute,
  } as any)
const DashboardBuyerMyTaskRoute = DashboardBuyerMyTaskRouteImport.update({
  id: '/my-task',
  path: '/my-task',
  getParentRoute: () => DashboardBuyerRouteRoute,
} as any)
const DashboardBuyerHomeRoute = DashboardBuyerHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardBuyerRouteRoute,
} as any)
const DashboardBuyerAddTaskRoute = DashboardBuyerAddTaskRouteImport.update({
  id: '/add-task',
  path: '/add-task',
  getParentRoute: () => DashboardBuyerRouteRoute,
} as any)
const DashboardAdminHomeRoute = DashboardAdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/buyer': typeof DashboardBuyerRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/worker': typeof DashboardWorkerRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/admin/home': typeof DashboardAdminHomeRoute
  '/dashboard/buyer/add-task': typeof DashboardBuyerAddTaskRoute
  '/dashboard/buyer/home': typeof DashboardBuyerHomeRoute
  '/dashboard/buyer/my-task': typeof DashboardBuyerMyTaskRoute
  '/dashboard/buyer/payment-history': typeof DashboardBuyerPaymentHistoryRoute
  '/dashboard/buyer/purchase-coins': typeof DashboardBuyerPurchaseCoinsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/buyer/': typeof DashboardBuyerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/worker': typeof DashboardWorkerRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/admin/home': typeof DashboardAdminHomeRoute
  '/dashboard/buyer/add-task': typeof DashboardBuyerAddTaskRoute
  '/dashboard/buyer/home': typeof DashboardBuyerHomeRoute
  '/dashboard/buyer/my-task': typeof DashboardBuyerMyTaskRoute
  '/dashboard/buyer/payment-history': typeof DashboardBuyerPaymentHistoryRoute
  '/dashboard/buyer/purchase-coins': typeof DashboardBuyerPurchaseCoinsRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/buyer': typeof DashboardBuyerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/buyer': typeof DashboardBuyerRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/worker': typeof DashboardWorkerRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/admin/home': typeof DashboardAdminHomeRoute
  '/dashboard/buyer/add-task': typeof DashboardBuyerAddTaskRoute
  '/dashboard/buyer/home': typeof DashboardBuyerHomeRoute
  '/dashboard/buyer/my-task': typeof DashboardBuyerMyTaskRoute
  '/dashboard/buyer/payment-history': typeof DashboardBuyerPaymentHistoryRoute
  '/dashboard/buyer/purchase-coins': typeof DashboardBuyerPurchaseCoinsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/buyer/': typeof DashboardBuyerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/buyer'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/worker'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/admin/home'
    | '/dashboard/buyer/add-task'
    | '/dashboard/buyer/home'
    | '/dashboard/buyer/my-task'
    | '/dashboard/buyer/payment-history'
    | '/dashboard/buyer/purchase-coins'
    | '/dashboard/admin/'
    | '/dashboard/buyer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/worker'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/admin/home'
    | '/dashboard/buyer/add-task'
    | '/dashboard/buyer/home'
    | '/dashboard/buyer/my-task'
    | '/dashboard/buyer/payment-history'
    | '/dashboard/buyer/purchase-coins'
    | '/dashboard/admin'
    | '/dashboard/buyer'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/buyer'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/worker'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/admin/home'
    | '/dashboard/buyer/add-task'
    | '/dashboard/buyer/home'
    | '/dashboard/buyer/my-task'
    | '/dashboard/buyer/payment-history'
    | '/dashboard/buyer/purchase-coins'
    | '/dashboard/admin/'
    | '/dashboard/buyer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/worker': {
      id: '/dashboard/worker'
      path: '/worker'
      fullPath: '/dashboard/worker'
      preLoaderRoute: typeof DashboardWorkerRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/buyer': {
      id: '/dashboard/buyer'
      path: '/buyer'
      fullPath: '/dashboard/buyer'
      preLoaderRoute: typeof DashboardBuyerRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/buyer/': {
      id: '/dashboard/buyer/'
      path: '/'
      fullPath: '/dashboard/buyer/'
      preLoaderRoute: typeof DashboardBuyerIndexRouteImport
      parentRoute: typeof DashboardBuyerRouteRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/buyer/purchase-coins': {
      id: '/dashboard/buyer/purchase-coins'
      path: '/purchase-coins'
      fullPath: '/dashboard/buyer/purchase-coins'
      preLoaderRoute: typeof DashboardBuyerPurchaseCoinsRouteImport
      parentRoute: typeof DashboardBuyerRouteRoute
    }
    '/dashboard/buyer/payment-history': {
      id: '/dashboard/buyer/payment-history'
      path: '/payment-history'
      fullPath: '/dashboard/buyer/payment-history'
      preLoaderRoute: typeof DashboardBuyerPaymentHistoryRouteImport
      parentRoute: typeof DashboardBuyerRouteRoute
    }
    '/dashboard/buyer/my-task': {
      id: '/dashboard/buyer/my-task'
      path: '/my-task'
      fullPath: '/dashboard/buyer/my-task'
      preLoaderRoute: typeof DashboardBuyerMyTaskRouteImport
      parentRoute: typeof DashboardBuyerRouteRoute
    }
    '/dashboard/buyer/home': {
      id: '/dashboard/buyer/home'
      path: '/home'
      fullPath: '/dashboard/buyer/home'
      preLoaderRoute: typeof DashboardBuyerHomeRouteImport
      parentRoute: typeof DashboardBuyerRouteRoute
    }
    '/dashboard/buyer/add-task': {
      id: '/dashboard/buyer/add-task'
      path: '/add-task'
      fullPath: '/dashboard/buyer/add-task'
      preLoaderRoute: typeof DashboardBuyerAddTaskRouteImport
      parentRoute: typeof DashboardBuyerRouteRoute
    }
    '/dashboard/admin/home': {
      id: '/dashboard/admin/home'
      path: '/home'
      fullPath: '/dashboard/admin/home'
      preLoaderRoute: typeof DashboardAdminHomeRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardAdminRouteRouteChildren {
  DashboardAdminHomeRoute: typeof DashboardAdminHomeRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteRouteChildren: DashboardAdminRouteRouteChildren = {
  DashboardAdminHomeRoute: DashboardAdminHomeRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteRouteWithChildren =
  DashboardAdminRouteRoute._addFileChildren(DashboardAdminRouteRouteChildren)

interface DashboardBuyerRouteRouteChildren {
  DashboardBuyerAddTaskRoute: typeof DashboardBuyerAddTaskRoute
  DashboardBuyerHomeRoute: typeof DashboardBuyerHomeRoute
  DashboardBuyerMyTaskRoute: typeof DashboardBuyerMyTaskRoute
  DashboardBuyerPaymentHistoryRoute: typeof DashboardBuyerPaymentHistoryRoute
  DashboardBuyerPurchaseCoinsRoute: typeof DashboardBuyerPurchaseCoinsRoute
  DashboardBuyerIndexRoute: typeof DashboardBuyerIndexRoute
}

const DashboardBuyerRouteRouteChildren: DashboardBuyerRouteRouteChildren = {
  DashboardBuyerAddTaskRoute: DashboardBuyerAddTaskRoute,
  DashboardBuyerHomeRoute: DashboardBuyerHomeRoute,
  DashboardBuyerMyTaskRoute: DashboardBuyerMyTaskRoute,
  DashboardBuyerPaymentHistoryRoute: DashboardBuyerPaymentHistoryRoute,
  DashboardBuyerPurchaseCoinsRoute: DashboardBuyerPurchaseCoinsRoute,
  DashboardBuyerIndexRoute: DashboardBuyerIndexRoute,
}

const DashboardBuyerRouteRouteWithChildren =
  DashboardBuyerRouteRoute._addFileChildren(DashboardBuyerRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAdminRouteRoute: typeof DashboardAdminRouteRouteWithChildren
  DashboardBuyerRouteRoute: typeof DashboardBuyerRouteRouteWithChildren
  DashboardWorkerRoute: typeof DashboardWorkerRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminRouteRoute: DashboardAdminRouteRouteWithChildren,
  DashboardBuyerRouteRoute: DashboardBuyerRouteRouteWithChildren,
  DashboardWorkerRoute: DashboardWorkerRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
