/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DashboardWorkerRouteRouteImport } from './routes/dashboard/worker/route'
import { Route as DashboardBuyerRouteRouteImport } from './routes/dashboard/buyer/route'
import { Route as DashboardAdminRouteRouteImport } from './routes/dashboard/admin/route'
import { Route as DashboardWorkerIndexRouteImport } from './routes/dashboard/worker/index'
import { Route as DashboardBuyerIndexRouteImport } from './routes/dashboard/buyer/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as ApiTaskIndexRouteImport } from './routes/api/task/index'
import { Route as ApiSubmissionIndexRouteImport } from './routes/api/submission/index'
import { Route as DashboardWorkerWithdrawalsRouteImport } from './routes/dashboard/worker/withdrawals'
import { Route as DashboardWorkerTaskListRouteImport } from './routes/dashboard/worker/task-list'
import { Route as DashboardWorkerSubmissionsRouteImport } from './routes/dashboard/worker/submissions'
import { Route as DashboardWorkerHomeRouteImport } from './routes/dashboard/worker/home'
import { Route as DashboardBuyerPurchaseCoinsRouteImport } from './routes/dashboard/buyer/purchase-coins'
import { Route as DashboardBuyerPaymentHistoryRouteImport } from './routes/dashboard/buyer/payment-history'
import { Route as DashboardBuyerMyTaskRouteImport } from './routes/dashboard/buyer/my-task'
import { Route as DashboardBuyerHomeRouteImport } from './routes/dashboard/buyer/home'
import { Route as DashboardBuyerAddTaskRouteImport } from './routes/dashboard/buyer/add-task'
import { Route as DashboardAdminWithdrawRequestsRouteImport } from './routes/dashboard/admin/withdraw-requests'
import { Route as DashboardAdminManageUserRouteImport } from './routes/dashboard/admin/manage-user'
import { Route as DashboardAdminManageTaskRouteImport } from './routes/dashboard/admin/manage-task'
import { Route as DashboardAdminHomeRouteImport } from './routes/dashboard/admin/home'
import { Route as ApiTaskIdRouteImport } from './routes/api/task/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardWorkerRouteRoute = DashboardWorkerRouteRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBuyerRouteRoute = DashboardBuyerRouteRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminRouteRoute = DashboardAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWorkerIndexRoute = DashboardWorkerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardWorkerRouteRoute,
} as any)
const DashboardBuyerIndexRoute = DashboardBuyerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardBuyerRouteRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const ApiTaskIndexRoute = ApiTaskIndexRouteImport.update({
  id: '/api/task/',
  path: '/api/task/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmissionIndexRoute = ApiSubmissionIndexRouteImport.update({
  id: '/api/submission/',
  path: '/api/submission/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkerWithdrawalsRoute =
  DashboardWorkerWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => DashboardWorkerRouteRoute,
  } as any)
const DashboardWorkerTaskListRoute = DashboardWorkerTaskListRouteImport.update({
  id: '/task-list',
  path: '/task-list',
  getParentRoute: () => DashboardWorkerRouteRoute,
} as any)
const DashboardWorkerSubmissionsRoute =
  DashboardWorkerSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => DashboardWorkerRouteRoute,
  } as any)
const DashboardWorkerHomeRoute = DashboardWorkerHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardWorkerRouteRoute,
} as any)
const DashboardBuyerPurchaseCoinsRoute =
  DashboardBuyerPurchaseCoinsRouteImport.update({
    id: '/purchase-coins',
    path: '/purchase-coins',
    getParentRoute: () => DashboardBuyerRouteRoute,
  } as any)
const DashboardBuyerPaymentHistoryRoute =
  DashboardBuyerPaymentHistoryRouteImport.update({
    id: '/payment-history',
    path: '/payment-history',
    getParentRoute: () => DashboardBuyerRouteRoute,
  } as any)
const DashboardBuyerMyTaskRoute = DashboardBuyerMyTaskRouteImport.update({
  id: '/my-task',
  path: '/my-task',
  getParentRoute: () => DashboardBuyerRouteRoute,
} as any)
const DashboardBuyerHomeRoute = DashboardBuyerHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardBuyerRouteRoute,
} as any)
const DashboardBuyerAddTaskRoute = DashboardBuyerAddTaskRouteImport.update({
  id: '/add-task',
  path: '/add-task',
  getParentRoute: () => DashboardBuyerRouteRoute,
} as any)
const DashboardAdminWithdrawRequestsRoute =
  DashboardAdminWithdrawRequestsRouteImport.update({
    id: '/withdraw-requests',
    path: '/withdraw-requests',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminManageUserRoute =
  DashboardAdminManageUserRouteImport.update({
    id: '/manage-user',
    path: '/manage-user',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminManageTaskRoute =
  DashboardAdminManageTaskRouteImport.update({
    id: '/manage-task',
    path: '/manage-task',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminHomeRoute = DashboardAdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const ApiTaskIdRoute = ApiTaskIdRouteImport.update({
  id: '/api/task/$id',
  path: '/api/task/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/buyer': typeof DashboardBuyerRouteRouteWithChildren
  '/dashboard/worker': typeof DashboardWorkerRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/task/$id': typeof ApiTaskIdRoute
  '/dashboard/admin/home': typeof DashboardAdminHomeRoute
  '/dashboard/admin/manage-task': typeof DashboardAdminManageTaskRoute
  '/dashboard/admin/manage-user': typeof DashboardAdminManageUserRoute
  '/dashboard/admin/withdraw-requests': typeof DashboardAdminWithdrawRequestsRoute
  '/dashboard/buyer/add-task': typeof DashboardBuyerAddTaskRoute
  '/dashboard/buyer/home': typeof DashboardBuyerHomeRoute
  '/dashboard/buyer/my-task': typeof DashboardBuyerMyTaskRoute
  '/dashboard/buyer/payment-history': typeof DashboardBuyerPaymentHistoryRoute
  '/dashboard/buyer/purchase-coins': typeof DashboardBuyerPurchaseCoinsRoute
  '/dashboard/worker/home': typeof DashboardWorkerHomeRoute
  '/dashboard/worker/submissions': typeof DashboardWorkerSubmissionsRoute
  '/dashboard/worker/task-list': typeof DashboardWorkerTaskListRoute
  '/dashboard/worker/withdrawals': typeof DashboardWorkerWithdrawalsRoute
  '/api/submission/': typeof ApiSubmissionIndexRoute
  '/api/task/': typeof ApiTaskIndexRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/buyer/': typeof DashboardBuyerIndexRoute
  '/dashboard/worker/': typeof DashboardWorkerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/task/$id': typeof ApiTaskIdRoute
  '/dashboard/admin/home': typeof DashboardAdminHomeRoute
  '/dashboard/admin/manage-task': typeof DashboardAdminManageTaskRoute
  '/dashboard/admin/manage-user': typeof DashboardAdminManageUserRoute
  '/dashboard/admin/withdraw-requests': typeof DashboardAdminWithdrawRequestsRoute
  '/dashboard/buyer/add-task': typeof DashboardBuyerAddTaskRoute
  '/dashboard/buyer/home': typeof DashboardBuyerHomeRoute
  '/dashboard/buyer/my-task': typeof DashboardBuyerMyTaskRoute
  '/dashboard/buyer/payment-history': typeof DashboardBuyerPaymentHistoryRoute
  '/dashboard/buyer/purchase-coins': typeof DashboardBuyerPurchaseCoinsRoute
  '/dashboard/worker/home': typeof DashboardWorkerHomeRoute
  '/dashboard/worker/submissions': typeof DashboardWorkerSubmissionsRoute
  '/dashboard/worker/task-list': typeof DashboardWorkerTaskListRoute
  '/dashboard/worker/withdrawals': typeof DashboardWorkerWithdrawalsRoute
  '/api/submission': typeof ApiSubmissionIndexRoute
  '/api/task': typeof ApiTaskIndexRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/buyer': typeof DashboardBuyerIndexRoute
  '/dashboard/worker': typeof DashboardWorkerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/buyer': typeof DashboardBuyerRouteRouteWithChildren
  '/dashboard/worker': typeof DashboardWorkerRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/task/$id': typeof ApiTaskIdRoute
  '/dashboard/admin/home': typeof DashboardAdminHomeRoute
  '/dashboard/admin/manage-task': typeof DashboardAdminManageTaskRoute
  '/dashboard/admin/manage-user': typeof DashboardAdminManageUserRoute
  '/dashboard/admin/withdraw-requests': typeof DashboardAdminWithdrawRequestsRoute
  '/dashboard/buyer/add-task': typeof DashboardBuyerAddTaskRoute
  '/dashboard/buyer/home': typeof DashboardBuyerHomeRoute
  '/dashboard/buyer/my-task': typeof DashboardBuyerMyTaskRoute
  '/dashboard/buyer/payment-history': typeof DashboardBuyerPaymentHistoryRoute
  '/dashboard/buyer/purchase-coins': typeof DashboardBuyerPurchaseCoinsRoute
  '/dashboard/worker/home': typeof DashboardWorkerHomeRoute
  '/dashboard/worker/submissions': typeof DashboardWorkerSubmissionsRoute
  '/dashboard/worker/task-list': typeof DashboardWorkerTaskListRoute
  '/dashboard/worker/withdrawals': typeof DashboardWorkerWithdrawalsRoute
  '/api/submission/': typeof ApiSubmissionIndexRoute
  '/api/task/': typeof ApiTaskIndexRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/buyer/': typeof DashboardBuyerIndexRoute
  '/dashboard/worker/': typeof DashboardWorkerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/buyer'
    | '/dashboard/worker'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/task/$id'
    | '/dashboard/admin/home'
    | '/dashboard/admin/manage-task'
    | '/dashboard/admin/manage-user'
    | '/dashboard/admin/withdraw-requests'
    | '/dashboard/buyer/add-task'
    | '/dashboard/buyer/home'
    | '/dashboard/buyer/my-task'
    | '/dashboard/buyer/payment-history'
    | '/dashboard/buyer/purchase-coins'
    | '/dashboard/worker/home'
    | '/dashboard/worker/submissions'
    | '/dashboard/worker/task-list'
    | '/dashboard/worker/withdrawals'
    | '/api/submission/'
    | '/api/task/'
    | '/dashboard/admin/'
    | '/dashboard/buyer/'
    | '/dashboard/worker/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/task/$id'
    | '/dashboard/admin/home'
    | '/dashboard/admin/manage-task'
    | '/dashboard/admin/manage-user'
    | '/dashboard/admin/withdraw-requests'
    | '/dashboard/buyer/add-task'
    | '/dashboard/buyer/home'
    | '/dashboard/buyer/my-task'
    | '/dashboard/buyer/payment-history'
    | '/dashboard/buyer/purchase-coins'
    | '/dashboard/worker/home'
    | '/dashboard/worker/submissions'
    | '/dashboard/worker/task-list'
    | '/dashboard/worker/withdrawals'
    | '/api/submission'
    | '/api/task'
    | '/dashboard/admin'
    | '/dashboard/buyer'
    | '/dashboard/worker'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/buyer'
    | '/dashboard/worker'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/task/$id'
    | '/dashboard/admin/home'
    | '/dashboard/admin/manage-task'
    | '/dashboard/admin/manage-user'
    | '/dashboard/admin/withdraw-requests'
    | '/dashboard/buyer/add-task'
    | '/dashboard/buyer/home'
    | '/dashboard/buyer/my-task'
    | '/dashboard/buyer/payment-history'
    | '/dashboard/buyer/purchase-coins'
    | '/dashboard/worker/home'
    | '/dashboard/worker/submissions'
    | '/dashboard/worker/task-list'
    | '/dashboard/worker/withdrawals'
    | '/api/submission/'
    | '/api/task/'
    | '/dashboard/admin/'
    | '/dashboard/buyer/'
    | '/dashboard/worker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTaskIdRoute: typeof ApiTaskIdRoute
  ApiSubmissionIndexRoute: typeof ApiSubmissionIndexRoute
  ApiTaskIndexRoute: typeof ApiTaskIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/worker': {
      id: '/dashboard/worker'
      path: '/worker'
      fullPath: '/dashboard/worker'
      preLoaderRoute: typeof DashboardWorkerRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/buyer': {
      id: '/dashboard/buyer'
      path: '/buyer'
      fullPath: '/dashboard/buyer'
      preLoaderRoute: typeof DashboardBuyerRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/worker/': {
      id: '/dashboard/worker/'
      path: '/'
      fullPath: '/dashboard/worker/'
      preLoaderRoute: typeof DashboardWorkerIndexRouteImport
      parentRoute: typeof DashboardWorkerRouteRoute
    }
    '/dashboard/buyer/': {
      id: '/dashboard/buyer/'
      path: '/'
      fullPath: '/dashboard/buyer/'
      preLoaderRoute: typeof DashboardBuyerIndexRouteImport
      parentRoute: typeof DashboardBuyerRouteRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/api/task/': {
      id: '/api/task/'
      path: '/api/task'
      fullPath: '/api/task/'
      preLoaderRoute: typeof ApiTaskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submission/': {
      id: '/api/submission/'
      path: '/api/submission'
      fullPath: '/api/submission/'
      preLoaderRoute: typeof ApiSubmissionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/worker/withdrawals': {
      id: '/dashboard/worker/withdrawals'
      path: '/withdrawals'
      fullPath: '/dashboard/worker/withdrawals'
      preLoaderRoute: typeof DashboardWorkerWithdrawalsRouteImport
      parentRoute: typeof DashboardWorkerRouteRoute
    }
    '/dashboard/worker/task-list': {
      id: '/dashboard/worker/task-list'
      path: '/task-list'
      fullPath: '/dashboard/worker/task-list'
      preLoaderRoute: typeof DashboardWorkerTaskListRouteImport
      parentRoute: typeof DashboardWorkerRouteRoute
    }
    '/dashboard/worker/submissions': {
      id: '/dashboard/worker/submissions'
      path: '/submissions'
      fullPath: '/dashboard/worker/submissions'
      preLoaderRoute: typeof DashboardWorkerSubmissionsRouteImport
      parentRoute: typeof DashboardWorkerRouteRoute
    }
    '/dashboard/worker/home': {
      id: '/dashboard/worker/home'
      path: '/home'
      fullPath: '/dashboard/worker/home'
      preLoaderRoute: typeof DashboardWorkerHomeRouteImport
      parentRoute: typeof DashboardWorkerRouteRoute
    }
    '/dashboard/buyer/purchase-coins': {
      id: '/dashboard/buyer/purchase-coins'
      path: '/purchase-coins'
      fullPath: '/dashboard/buyer/purchase-coins'
      preLoaderRoute: typeof DashboardBuyerPurchaseCoinsRouteImport
      parentRoute: typeof DashboardBuyerRouteRoute
    }
    '/dashboard/buyer/payment-history': {
      id: '/dashboard/buyer/payment-history'
      path: '/payment-history'
      fullPath: '/dashboard/buyer/payment-history'
      preLoaderRoute: typeof DashboardBuyerPaymentHistoryRouteImport
      parentRoute: typeof DashboardBuyerRouteRoute
    }
    '/dashboard/buyer/my-task': {
      id: '/dashboard/buyer/my-task'
      path: '/my-task'
      fullPath: '/dashboard/buyer/my-task'
      preLoaderRoute: typeof DashboardBuyerMyTaskRouteImport
      parentRoute: typeof DashboardBuyerRouteRoute
    }
    '/dashboard/buyer/home': {
      id: '/dashboard/buyer/home'
      path: '/home'
      fullPath: '/dashboard/buyer/home'
      preLoaderRoute: typeof DashboardBuyerHomeRouteImport
      parentRoute: typeof DashboardBuyerRouteRoute
    }
    '/dashboard/buyer/add-task': {
      id: '/dashboard/buyer/add-task'
      path: '/add-task'
      fullPath: '/dashboard/buyer/add-task'
      preLoaderRoute: typeof DashboardBuyerAddTaskRouteImport
      parentRoute: typeof DashboardBuyerRouteRoute
    }
    '/dashboard/admin/withdraw-requests': {
      id: '/dashboard/admin/withdraw-requests'
      path: '/withdraw-requests'
      fullPath: '/dashboard/admin/withdraw-requests'
      preLoaderRoute: typeof DashboardAdminWithdrawRequestsRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/manage-user': {
      id: '/dashboard/admin/manage-user'
      path: '/manage-user'
      fullPath: '/dashboard/admin/manage-user'
      preLoaderRoute: typeof DashboardAdminManageUserRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/manage-task': {
      id: '/dashboard/admin/manage-task'
      path: '/manage-task'
      fullPath: '/dashboard/admin/manage-task'
      preLoaderRoute: typeof DashboardAdminManageTaskRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/home': {
      id: '/dashboard/admin/home'
      path: '/home'
      fullPath: '/dashboard/admin/home'
      preLoaderRoute: typeof DashboardAdminHomeRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/api/task/$id': {
      id: '/api/task/$id'
      path: '/api/task/$id'
      fullPath: '/api/task/$id'
      preLoaderRoute: typeof ApiTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardAdminRouteRouteChildren {
  DashboardAdminHomeRoute: typeof DashboardAdminHomeRoute
  DashboardAdminManageTaskRoute: typeof DashboardAdminManageTaskRoute
  DashboardAdminManageUserRoute: typeof DashboardAdminManageUserRoute
  DashboardAdminWithdrawRequestsRoute: typeof DashboardAdminWithdrawRequestsRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteRouteChildren: DashboardAdminRouteRouteChildren = {
  DashboardAdminHomeRoute: DashboardAdminHomeRoute,
  DashboardAdminManageTaskRoute: DashboardAdminManageTaskRoute,
  DashboardAdminManageUserRoute: DashboardAdminManageUserRoute,
  DashboardAdminWithdrawRequestsRoute: DashboardAdminWithdrawRequestsRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteRouteWithChildren =
  DashboardAdminRouteRoute._addFileChildren(DashboardAdminRouteRouteChildren)

interface DashboardBuyerRouteRouteChildren {
  DashboardBuyerAddTaskRoute: typeof DashboardBuyerAddTaskRoute
  DashboardBuyerHomeRoute: typeof DashboardBuyerHomeRoute
  DashboardBuyerMyTaskRoute: typeof DashboardBuyerMyTaskRoute
  DashboardBuyerPaymentHistoryRoute: typeof DashboardBuyerPaymentHistoryRoute
  DashboardBuyerPurchaseCoinsRoute: typeof DashboardBuyerPurchaseCoinsRoute
  DashboardBuyerIndexRoute: typeof DashboardBuyerIndexRoute
}

const DashboardBuyerRouteRouteChildren: DashboardBuyerRouteRouteChildren = {
  DashboardBuyerAddTaskRoute: DashboardBuyerAddTaskRoute,
  DashboardBuyerHomeRoute: DashboardBuyerHomeRoute,
  DashboardBuyerMyTaskRoute: DashboardBuyerMyTaskRoute,
  DashboardBuyerPaymentHistoryRoute: DashboardBuyerPaymentHistoryRoute,
  DashboardBuyerPurchaseCoinsRoute: DashboardBuyerPurchaseCoinsRoute,
  DashboardBuyerIndexRoute: DashboardBuyerIndexRoute,
}

const DashboardBuyerRouteRouteWithChildren =
  DashboardBuyerRouteRoute._addFileChildren(DashboardBuyerRouteRouteChildren)

interface DashboardWorkerRouteRouteChildren {
  DashboardWorkerHomeRoute: typeof DashboardWorkerHomeRoute
  DashboardWorkerSubmissionsRoute: typeof DashboardWorkerSubmissionsRoute
  DashboardWorkerTaskListRoute: typeof DashboardWorkerTaskListRoute
  DashboardWorkerWithdrawalsRoute: typeof DashboardWorkerWithdrawalsRoute
  DashboardWorkerIndexRoute: typeof DashboardWorkerIndexRoute
}

const DashboardWorkerRouteRouteChildren: DashboardWorkerRouteRouteChildren = {
  DashboardWorkerHomeRoute: DashboardWorkerHomeRoute,
  DashboardWorkerSubmissionsRoute: DashboardWorkerSubmissionsRoute,
  DashboardWorkerTaskListRoute: DashboardWorkerTaskListRoute,
  DashboardWorkerWithdrawalsRoute: DashboardWorkerWithdrawalsRoute,
  DashboardWorkerIndexRoute: DashboardWorkerIndexRoute,
}

const DashboardWorkerRouteRouteWithChildren =
  DashboardWorkerRouteRoute._addFileChildren(DashboardWorkerRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAdminRouteRoute: typeof DashboardAdminRouteRouteWithChildren
  DashboardBuyerRouteRoute: typeof DashboardBuyerRouteRouteWithChildren
  DashboardWorkerRouteRoute: typeof DashboardWorkerRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminRouteRoute: DashboardAdminRouteRouteWithChildren,
  DashboardBuyerRouteRoute: DashboardBuyerRouteRouteWithChildren,
  DashboardWorkerRouteRoute: DashboardWorkerRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTaskIdRoute: ApiTaskIdRoute,
  ApiSubmissionIndexRoute: ApiSubmissionIndexRoute,
  ApiTaskIndexRoute: ApiTaskIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
